package com.hariomahlawat.bannedappdetector

val unwantedAppsList = listOf(
    MonitoredAppMeta("com.jungleerummy.playcashgameonline", "Junglee Rummy Cash", AppCategory.UNWANTED),
    MonitoredAppMeta("com.xinnew22gm.utiltysshow.twfunny", "TeenPatti MPL Rummy Online", AppCategory.UNWANTED),
    MonitoredAppMeta("com.games24x7.rummycircle.rummy", "RummyCircle Real Cash Rummy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.jungleegames.rummy", "Junglee Rummy Play Rummy Game", AppCategory.UNWANTED),
    MonitoredAppMeta("com.rozclient.game", "RozRummy Indian Rummy Online", AppCategory.UNWANTED),
    MonitoredAppMeta("com.seclife.callbreak", "Call Break Online Tash Game", AppCategory.UNWANTED),
    MonitoredAppMeta("com.ironman.rummy365two.india.mightygame", "Rummy365 Games", AppCategory.UNWANTED),
    MonitoredAppMeta("com.comfun.mobile.rumm.asgp", "Indian Rummy Comfun Online", AppCategory.UNWANTED),
    MonitoredAppMeta("com.teenpatti.hd.gold.rummy", "Rummy Gold With Fast Rummy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.teenpatti.hd.gold", "TeenPatti Gold 3Patti Rummy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.octro.teenpatti", "TeenPatti Octro 3Patti Rummy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.octro.rummy", "Indian Rummy TeenPatti Rummy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.bbumgames.rummystars", "Gin Rummy Stars Card Game", AppCategory.UNWANTED),
    MonitoredAppMeta("com.hyilmaz.rummy.gin", "Gin Rummy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.bbumgames.rummyrush", "Rummy Rush Classic Card Game", AppCategory.UNWANTED),
    MonitoredAppMeta("funnyplay.rresd.card.needshine", "TeenPatti Star 3Patti Online", AppCategory.UNWANTED),
    MonitoredAppMeta("lead.happygame.trfstar.esdf.together", "TeenPatti Star TeenPatti Online", AppCategory.UNWANTED),
    MonitoredAppMeta("com.okizvngcom.ktumnhqqwiixcir", "TeenPatti Star", AppCategory.UNWANTED),
    MonitoredAppMeta("com.pare.prop.wly", "TeenPatti Go 3Patti Star", AppCategory.UNWANTED),
    MonitoredAppMeta("com.sweetgame.teenpatti", "TeenPatti Sweet", AppCategory.UNWANTED),
    MonitoredAppMeta("in.stargame.funcard.org", "TeenPatti Star India", AppCategory.UNWANTED),
    MonitoredAppMeta("com.games24x7.teenpatti.playstore", "UTP Ultimate Teen Patti 3P", AppCategory.UNWANTED),
    MonitoredAppMeta("com.games24x7.ultimaterummy.playstore", "Ultimate Rummy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.comfun.mobile.teen.asgp", "TeenPatti Comfun Card Online", AppCategory.UNWANTED),
    MonitoredAppMeta("com.dhamal.card", "TeenPatti Dhamal", AppCategory.UNWANTED),
    MonitoredAppMeta("com.octro.teenpattilive", "TeenPatti Live", AppCategory.UNWANTED),
    MonitoredAppMeta("air.com.ace2three.mobile", "A23 Games Rummy Fantasy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.online.real.indian.cards.palacerummy", "RummyPalace Play Rummy Online", AppCategory.UNWANTED),
    MonitoredAppMeta("com.howzatfantasy.play", "Howzat Fantasy Cricket App", AppCategory.UNWANTED),
    MonitoredAppMeta("com.gameskraft.rummyculturelite", "Rummy Game Play Rummy Online", AppCategory.UNWANTED),
    MonitoredAppMeta("com.rummywin.client", "RummyWin Play Rummy Game", AppCategory.UNWANTED),
    MonitoredAppMeta("com.ruby.rummy", "RubyRummy Indian Online Free", AppCategory.UNWANTED),
    MonitoredAppMeta("com.surprisegame.rc4.terminator", "RummyCool Indian Card Game", AppCategory.UNWANTED),
    MonitoredAppMeta("com.rucootinae.galoecmzyusci", "RummyCool", AppCategory.UNWANTED),
    MonitoredAppMeta("com.rumrummy.app", "RumRummy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.eastudios.rummy500", "Rummy500", AppCategory.UNWANTED),
    MonitoredAppMeta("com.eastudios.rummygold", "RummyGold", AppCategory.UNWANTED),
    MonitoredAppMeta("com.kashrummy.development", "Kash Rummy Playrummy game", AppCategory.UNWANTED),
    MonitoredAppMeta("com.rummybhai.app", "Rummy Bhai Online Card Game", AppCategory.UNWANTED),
    MonitoredAppMeta("io.yarsa.games.indianrummy", "Indian Rummy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.rummy.litegame", "RummyLite Online Indian Rummy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.tycoon2.coon2", "TeenPatti Tycoon", AppCategory.UNWANTED),
    MonitoredAppMeta("com.DashRummyDeveloper.App", "DashRummy Online Rummy Game", AppCategory.UNWANTED),
    MonitoredAppMeta("com.best.rummygame.raja", "RummyRaja 13 Card Game", AppCategory.UNWANTED),
    MonitoredAppMeta("com.rummycue.empty", "RummyCue Indian Rummy Online", AppCategory.UNWANTED),
    MonitoredAppMeta("com.indianrummy.onlinerummy.cardgames.taprummy", "TapRummy Play Rummy Game", AppCategory.UNWANTED),
    MonitoredAppMeta("com.super.winner.onlinegame", "SuperWinner Popular Games", AppCategory.UNWANTED),
    MonitoredAppMeta("com.rummytime.practice", "Rummytime Play Rummy Online", AppCategory.UNWANTED),
    MonitoredAppMeta("com.rummycircle.lite.android", "PlayRummy Game Rummy Circle", AppCategory.UNWANTED),
    MonitoredAppMeta("com.adda52.poker.free", "Adda52 Play Poker Games", AppCategory.UNWANTED),
    MonitoredAppMeta("com.vindhyainfotech.classicrummyfree", "Classic Rummy", AppCategory.UNWANTED),
    MonitoredAppMeta("com.lefkowitzaegxo.thirdlykzgm", "Rummy Hero Online Card", AppCategory.UNWANTED),
    MonitoredAppMeta("com.northskygames.RummyRoyale", "Rummy Royale", AppCategory.UNWANTED),
    MonitoredAppMeta("com.gamezy.lite", "Gamezy Play Online Games", AppCategory.UNWANTED),
    MonitoredAppMeta("com.nautilus.RealCricket3D", "Real Cricket 20", AppCategory.UNWANTED),
    MonitoredAppMeta("com.khelplay.rummy", "KhelPlay Rummy Online Rummy", AppCategory.UNWANTED),
    MonitoredAppMeta("bYLs.wnmV.nA8NiQ", "Rummy League Real", AppCategory.UNWANTED),
    MonitoredAppMeta("com.sport.brunoolivas", "PariMsports", AppCategory.UNWANTED),
    MonitoredAppMeta("org.betup", "Sports Betting Game BETUP", AppCategory.UNWANTED),
    MonitoredAppMeta("com.mw.rouletteroyale", "Roulette Royale Grand Casino", AppCategory.UNWANTED),
    MonitoredAppMeta("com.mywavia.teenpatti.android", "TeenPatti King Flush Poker", AppCategory.UNWANTED),
    MonitoredAppMeta("com.cashstorm.slots", "Cash Storm Slots Games", AppCategory.UNWANTED),
    MonitoredAppMeta("triwin.slots.jackpot.grand", "Grand Jackpot Slots Casino", AppCategory.UNWANTED),
    MonitoredAppMeta("triwin.casino.slots.fortune.gold", "Gold Fortune Slot Casino Game", AppCategory.UNWANTED),
    MonitoredAppMeta("jackpotboom.slots.casino.vegas.free.android", "Jackpot Boom Casino Slot Games", AppCategory.UNWANTED),
    MonitoredAppMeta("gambino.android", "Gambino Slots Online Casino", AppCategory.UNWANTED),
    MonitoredAppMeta("com.williamsinteractive.jackpotparty", "Jackpot Party Casino Slots", AppCategory.UNWANTED),
    MonitoredAppMeta("com.ballytechnologies.quickhitslots", "Quick Hit Casino Slot Games", AppCategory.UNWANTED),
    MonitoredAppMeta("com.scientificgames.monopolyslots", "MONOPOLY Slots Casino Games", AppCategory.UNWANTED),
    MonitoredAppMeta("com.bagelcode.slots1", "Club Vegas Slots Casino Games", AppCategory.UNWANTED),
    MonitoredAppMeta("com.huuuge.casino.slots", "Huuuge Casino Slots Vegas 777", AppCategory.UNWANTED),
    MonitoredAppMeta("com.stgame.slots.cash", "Cash Blitz Slots Casino Games", AppCategory.UNWANTED),
    MonitoredAppMeta("air.com.playtika.slotomania", "Slotomania Slots Casino Games", AppCategory.UNWANTED),
    MonitoredAppMeta("com.GoldenLuck.LuckyRewards.MakeBigMoney.RealCashOut", "Golden Money Luck Cash Slots", AppCategory.UNWANTED),
    MonitoredAppMeta("com.spinforcash.casino.lucky.jackpot.big.win", "Spin for Cash Real Money Slot", AppCategory.UNWANTED),
    MonitoredAppMeta("com.huuuge.casino.texas", "Billionaire Casino Slots 777", AppCategory.UNWANTED),
    MonitoredAppMeta("com.slotslimited.goldencasino", "Golden Casino Vegas Slots", AppCategory.UNWANTED),
    MonitoredAppMeta("slots.pcg.casino.games.free.android", "Cash Frenz Casino Slots", AppCategory.UNWANTED),
    MonitoredAppMeta("com.trpz.travel", "Match To Win Win Real Cash", AppCategory.UNWANTED),
    MonitoredAppMeta("com.gsn.grandcasino", "Grand Casino Slots Bingo", AppCategory.UNWANTED),
    MonitoredAppMeta("com.playtika.caesarscasino", "Caesars Slots Casino games", AppCategory.UNWANTED),
    MonitoredAppMeta("com.gsn.android.casino", "GSN Casino Sloachine Games", AppCategory.UNWANTED),
    MonitoredAppMeta("com.selfawaregames.acecasino", "Big Fish Casino Social Slots", AppCategory.UNWANTED),
    MonitoredAppMeta("de.whow.jackpot", "My Jackpot Slots Casino", AppCategory.UNWANTED),
    MonitoredAppMeta("com.platogo.pmp", "Slotpark Online Casino Games", AppCategory.UNWANTED),
    MonitoredAppMeta("eu.mvns.games", "BlackJack 21 Online Casino", AppCategory.UNWANTED),
    MonitoredAppMeta("com.abzorbagames.roulette", "Roulette Live Real Casino", AppCategory.UNWANTED),
    MonitoredAppMeta("com.dream11.fantasy.cricket.football.kabaddi", "Dream11 Fantasy Cricket App", AppCategory.UNWANTED),
    MonitoredAppMeta("com.my11circle1.android", "My11Circle Lite Fantasy App", AppCategory.UNWANTED),
    MonitoredAppMeta("com.playtika.wsop.gp", "WSOP Poker Games Online", AppCategory.UNWANTED),
    MonitoredAppMeta("eu.ganymede.pokerhd", "Poker Texas Holdem Live Pro", AppCategory.UNWANTED),
    MonitoredAppMeta("com.lein.pppoker.android", "PPPoker Home Games", AppCategory.UNWANTED),
    MonitoredAppMeta("io.bbstud.pkc", "Poker Championship Holdem", AppCategory.UNWANTED),
    MonitoredAppMeta("com.slotman.candyapp", "Royal Panda Casino", AppCategory.UNWANTED),
    MonitoredAppMeta("com.infiapps.pandaslots", "Panda Slots", AppCategory.UNWANTED),
    MonitoredAppMeta("com.pacificinteractive.HouseOfFun", "House of Fun Casino Slots", AppCategory.UNWANTED),
    MonitoredAppMeta("com.nurigames.casinolive", "Galaxy Casino Live Slots", AppCategory.UNWANTED),
    MonitoredAppMeta("air.biz.rightshift.clickfun.casino", "Clickfun Casino Slots", AppCategory.UNWANTED),
    MonitoredAppMeta("com.aaagame.slots777", "Slots Vegas Casino Slot", AppCategory.UNWANTED),
    MonitoredAppMeta("com.triwin.lucky.dozer", "Lucky Cash Pusher Coin Games", AppCategory.UNWANTED),
    MonitoredAppMeta("com.gbwhatsapp", "GB WhatsApp", AppCategory.UNWANTED),
    MonitoredAppMeta("com.whatsapp.gb", "GB WhatsApp 2", AppCategory.UNWANTED),
    MonitoredAppMeta("com.gbwhatsapp2", "GB WhatsApp 3", AppCategory.UNWANTED),
    MonitoredAppMeta("com.whatsapp2.gb", "GB WhatsApp 4", AppCategory.UNWANTED),
    MonitoredAppMeta("com.gbwhatsapp3", "GB WhatsApp 5", AppCategory.UNWANTED),
    MonitoredAppMeta("com.whatsapp3.gb", "GB WhatsApp 6", AppCategory.UNWANTED),
    MonitoredAppMeta("io.beldex.bchat", "BChat Web3 Secure Messenger", AppCategory.UNWANTED)
)

val unwantedAppsAZ: Map<Char, List<String>> =
    unwantedAppsList.map { it.displayName }.groupBy { it.first().uppercaseChar() }
